a = float(input("A трикутника: "))
b = float(input("B трикутника: "))
c = float(input("C трикутника: "))
a1 = a/2
b1 = b/2
c1 = c/2
print(f"A сер. = {a1}")
print(f"B сер. = {b1}")
print(f"C сер. = {c1}")